### ISSUE TITLE
“ display(box_auto) NameError: name 'display' is not defined”

### ISSUE THREAD

**Issue by rockywind** [yuehaowang/RecolorNeRF#2]
Hi,
When I run the color_edit.py, I met the error below.
````
  File "/rockywin.wang/NeRF/RecolorNeRF/color_edit.py", line 141, in <module>
    display(box_auto)
NameError: name 'display' is not defined
````
I copyed the `color_edit.ipynb` to `color_edit.py`.

**Comment by yuehaowang** [comment]
Hi, thanks for your question.

The `display` function is defined in IPython and works on Jupyter Notebook.
Since we also use [Jupyter widgets](https://ipywidgets.readthedocs.io/en/stable/#jupyter-widgets) (e.g., color pickers) for user input, you need to do some adaptations to convert the notebook into a single python file, like change Jupyter widgets to native GUIs.

**Comment by rockywind** [comment]
Thanks a lot!
